# This is a basic workflow to help you get started with Actions

name: DockerBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dockergoexpert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      working-directory: ./goversion

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: GithubPackages-Docker
      uses: Kolkies/githubpackages-docker@v1.0.4
      with:
        # Access token which is used to deploy the image to the repository.
        repo-token:  ${{ secrets.GITHUB_TOKEN }}
        # Name for the docker image
        image-name: GoExpert
